move robust estimation to core
vxl/vxl pull request #913
Opened 2022-12-30 20:41 UTC by mundyj

## PR Checklist

-  [X]  --> Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
-  [X]  --> Makes design changes to existing vxl/core\* API that requires semantic versioning increase

-  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
-  [X]  --> Adds tests and baseline comparison (quantitative).
no_entry_sign: --> Adds Documentation.

2022-12-30 20:44 UTC, mundyj commented
Moved a library from contrib to minimize non-hierarchical library dependencies and expose a widely applicable set of robust algorithms.

2023-01-03 17:21 UTC, decrispell approved these changes

2023-01-04 19:06 UTC, decrispell requested changes

2023-01-04 19:06 UTC, decrispell commented on contrib/rpl/rgrl/tests/test_transformation.cxx
> +  // for the affine, the location is ivrelevant when transforming a
find&replace typo

2023-01-04 19:19 UTC, mundyj commented
Requested changes have been made

From: Daniel Crispell ***@***.***>
Sent: Wednesday, January 4, 2023 2:06 PM
To: vxl/vxl ***@***.***>
Cc: Joseph Mundy ***@***.***>; Author ***@***.***>
Subject: Re: [vxl/vxl] move robust estimation to core (PR #913)


@decrispell requested changes on this pull request.

________________________________

In contrib/rpl/rgrl/CMakeLists.txt<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fvxl%2Fvxl%2Fpull%2F913%23discussion_r1061794481&data=05%7C01%7Cjlm%40visionsystemsinc.com%7Cfe8052b6196b47199c7f08daee86c5f0%7C31917b2e93b247bd96b0430470e211be%7C0%7C0%7C638084559873380492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZRCq0B6TTC6NozPmRW6aBopKjhveDRwo%2BqBkLupwkHI%3D&reserved=0>:

> @@ -1,5 +1,5 @@

 doxygen_add_library(contrib/rpl/rgrl

-  DEPENDS contrib/rpl/rrel contrib/rpl/rsdl core/vnl core/vbl core/vil

+  DEPENDS contrib/rpl/vrel contrib/rpl/rsdl core/vnl core/vbl core/vil

should be core/vrel ?

________________________________

In contrib/rpl/rgrl/tests/test_transformation.cxx<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fvxl%2Fvxl%2Fpull%2F913%23discussion_r1061796419&data=05%7C01%7Cjlm%40visionsystemsinc.com%7Cfe8052b6196b47199c7f08daee86c5f0%7C31917b2e93b247bd96b0430470e211be%7C0%7C0%7C638084559873380492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZcWwtjvfmg3TFZFB80DFrFTKLWwQu%2BrQCBoYABHKtzk%3D&reserved=0>:

> @@ -78,7 +78,7 @@ test_trans_affine()



   vnl_vector<double> xformed_direction( 3 );



-  // for the affine, the location is irrelevant when transforming a

+  // for the affine, the location is ivrelevant when transforming a

find&replace typo

-
Reply to this email directly, view it on GitHub<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fvxl%2Fvxl%2Fpull%2F913%23pullrequestreview-1236345074&data=05%7C01%7Cjlm%40visionsystemsinc.com%7Cfe8052b6196b47199c7f08daee86c5f0%7C31917b2e93b247bd96b0430470e211be%7C0%7C0%7C638084559873380492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=B1wuXeY2kwJ8keukcdNxUphIPq64K6fRp02wSBzq8z0%3D&reserved=0>, or unsubscribe<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACEVBKUQT4STKNVQR5EK2UTWQXC27ANCNFSM6AAAAAATNEOBFA&data=05%7C01%7Cjlm%40visionsystemsinc.com%7Cfe8052b6196b47199c7f08daee86c5f0%7C31917b2e93b247bd96b0430470e211be%7C0%7C0%7C638084559873380492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JPLof94tq%2BSjm8P6YTd0DFDDEKURaLuGmVgrZuyMSrk%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2023-01-04 19:20 UTC, decrispell approved these changes

2023-01-05 21:35 UTC, merged