COMP: Replace sprintf to snprintf
vxl/vxl pull request #956
Opened 2024-07-05 21:23 UTC by andrei-sandor

Replacement of sprintf to snprintf.

Here only one fix is proposed since it involves doing more involved changes.

Here the snprintf requires the size of buf. Unfortunately, buf, without it’s length, is passed to the function.

We can also see that each function in the file has the same name and a argument list very similar for each of them.

I propose to create at the top a function that has the same name as the others, but with the length of buf added and snprintf used. Then, use that function for the other functions accordingly.

Can I proceed like this for the rest of the functions in the file? Also, should we add a deprecated comment?

2024-07-26 17:48 UTC, seanm commented
@decrispell @hjmjohnson So is it ok for us to proceed in this fashion, and change function signatures where necessary to bring along the buffer length?

2024-08-07 22:53 UTC, seanm requested changes

2024-08-07 22:53 UTC, seanm commented on core/vnl/vnl_matlab_print_scalar.cxx
> +vnl_matlab_print_scalar(int v, char * buf, size_t buf_len, vnl_matlab_print_format format)
You adding the parameter name `format` here might introduce a compiler warning about "format is unused". A common way to suppress such warnings is to remove the parameter name, which is probably why it was omitted. Not sure why you added it, but probably should remove it.  Not just on this line, but elsewhere below too.

2024-08-07 22:53 UTC, seanm commented on core/vnl/vnl_matlab_print_scalar.cxx
> +                  buf_len,
Here the 2nd parameter is wrong. Not matching the right buffer. Elsewhere too.

2024-08-07 22:53 UTC, seanm commented on core/vnl/vnl_matlab_print_scalar.h
> +VNL_EXPORT void vnl_matlab_print_scalar(T v, \
I think this could have `VXL_DEPRECATED` too, ie:

`VNL_EXPORT VXL_DEPRECATED void vnl_matlab_print_scalar(T v, \`

Worth a try anyway.

2024-08-08 14:44 UTC, seanm approved these changes

2024-08-08 14:46 UTC, seanm commented
@hjmjohnson this lgtm now, care to review? @andrei-sandor ends his internship with us next week, so ideally we could wrap this up by then.

2024-08-29 00:51 UTC, seanm commented
@hjmjohnson friendly ping...

2024-11-18 20:25 UTC, seanm commented
@hjmjohnson friendly ping...

2024-11-18 20:40 UTC, hjmjohnson approved these changes

2024-11-18 20:40 UTC, merged