Use cmake_minimum_required to set policy.
vxl/vxl pull request #966
Opened 2024-11-26 18:45 UTC by blowekamp

Add "...policy_max", sets the maximum policy, and avoid CMake deprecation warnings when the min version is too old.

## PR Checklist

-  Makes breaking changes to the vxl/core/\* API that requires semantic versioning increase
-  Makes design changes to existing vxl/core\* API that requires semantic versioning increase

-  Makes changes to the contributed directory API DOES NOT require semantic versioning increase
-  Adds tests and baseline comparison (quantitative).
-  Adds Documentation.

2024-11-26 23:36 UTC, blowekamp commented
@hjmjohnson Can you look at this?

2024-11-28 15:38 UTC, blowekamp commented
@dzenanz Can you please review?

2024-11-28 15:48 UTC, dzenanz requested changes
What happens with CMake versions between 3.10.2 and 3.12?

The existing logic seems to better cover these possibilities.

2024-11-28 16:15 UTC, blowekamp commented
It this same. From the documentation:

https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html
```
If the running version of CMake is older than 3.12, the extra ... dots will be seen as version component separators, resulting in the ...<max> part being ignored and preserving the pre-3.12 behavior of basing policies on <min>.
```

2024-11-28 16:22 UTC, dzenanz approved these changes

2024-12-03 14:04 UTC, blowekamp commented
Can this PR be merged?

2024-12-03 14:39 UTC, decrispell commented
> Can this PR be merged?

I was waiting on @hjmjohnson since you requested his review as well, but I'll go ahead and merge now.

2024-12-03 14:39 UTC, merged